### ISSUE TITLE
Generate_Api_Rest

### ISSUE THREAD

**Issue by Matiss2702** [Matiss2702/Exam-Git-IW#1]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Une description claire et concise de la nature du problème. Ex. Je suis toujours frustré quand [...]
Non

**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce que vous voulez qu'il se passe.
Générer l'api rest 

**Contexte supplémentaire**
Ajoutez ici tout autre contexte ou capture d'écran concernant la demande de fonctionnalité.

![image](https://user-images.githubusercontent.com/92375495/215278107-358e1663-3ff8-43b6-afe0-e52d23837d50.png)

**Comment by Beleguic** [comment]
API Rest Created
