### ISSUE TITLE
Dossier Admin dans le dossier Views

### ISSUE THREAD

**Issue by Beleguic** [Matiss2702/Exam-Git-IW#12]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Non, Aucun Probleme

**Décrivez la solution que vous souhaitez**
Le dossier Admin contiendra les dossiers cocktails et users
dans le dossier cocktail il y aura un fichier cocktailEdit et index
le fichier cocktailEdit permettra de modifié un cocktail donné le index 
permettra de voir tous les cocktails donnés

**Comment by Matiss2702** [comment]
feature_folder_admin_in_the_folder_views done
