### ISSUE TITLE
Dossier Auth

### ISSUE THREAD

**Issue by Beleguic** [Matiss2702/Exam-Git-IW#13]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Non, Aucun Probleme

**Décrivez la solution que vous souhaitez**
Le Dossier Auth aura un fichier login qui permettra de se connecté a l'admin grace au token generé par l'api et stocker dans le auth-guard

**Comment by Matiss2702** [comment]
feature_folder_auth done
