### ISSUE TITLE
Controlleur Authenfication

### ISSUE THREAD

**Issue by Matiss2702** [Matiss2702/Exam-Git-IW#15]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Une description claire et concise de la nature du problème. Ex. Je suis toujours frustré quand [...]
non
**Décrivez la solution que vous souhaitez**
Une description claire et concise de ce que vous voulez qu'il se passe.
Je veux un controller d'authenfication qui va controller l'authentification

**Comment by Beleguic** [comment]
controller auth added
