### ISSUE TITLE
Dossier Public dans le dossier views

### ISSUE THREAD

**Issue by Beleguic** [Matiss2702/Exam-Git-IW#16]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Non, Aucun Problème

**Décrivez la solution que vous souhaitez**
Le dossier public contiendra les vue de cocktail, contact, home, Layout et un fichier index.js qui exportera les views public

**Comment by Matiss2702** [comment]
feature_folder_public_in_the_folder_views done
