### ISSUE TITLE
Dossier Helper

### ISSUE THREAD

**Issue by Beleguic** [Matiss2702/Exam-Git-IW#4]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Aucun probleme

**Décrivez la solution que vous souhaitez**
Un dossier Helper qui contiendra un fichier auth-guard.js qui aura une fonction authGuard qui recuperera un token pour l'autentification

**Comment by Matiss2702** [comment]
feature_folder_helper done
