### ISSUE TITLE
Dossier _services

### ISSUE THREAD

**Issue by Beleguic** [Matiss2702/Exam-Git-IW#5]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez s'il vous plait.**
Non, Aucun Probleme

**Décrivez la solution que vous souhaitez**
Un dossier _service qui s'occupera de la connexion a l'api rest et qui permettra de save le token donne par l'api 
il pemettra aussi de gerer les users et cocktail soit des fonctions update, delete et create elle recupera aussi les users et cocktail

**Comment by Matiss2702** [comment]
feature_dossier_services done
